### ISSUE TITLE
1-to-N and M-to-N mappings don't divide source province weight across target provinces

### ISSUE THREAD

**Issue by MaxTheDesertManIran** [ParadoxGameConverters/EU4toVic2#624] opened 2020-11-20 17:39 UTC
Hello there.
Firstly, I must thank you guys for making such an amazing tool and improving it regularly with updates!
Now, I feel like the absolute dev conversion feature was not intended to be used that often, and was just meant as a secondary option similar to the full culture conversion feature; and is not a priority in development.
But I have nonetheless found a few flaws with it, and have a few suggestions.
### Multiple Province Mappings
I have noticed that the converter, when converting **multiple** EU4 provinces to **one** in Vic2, _averages_ the weight of the EU4 provinces and converts it to Vic2.
And when converting **one** province from EU4 into **multiple** in Vic2, it _multiplies_ it.
I feel like this was intended to be the other way, as this causes some oddities. (And **major** unbalances with places this is common, like India)
Such as Bukhara (a 50 dev, high income, high manpower province in my game) being watered down due to it being ridiculously big in Vic2 and also covering the 3 low-dev EU4 provinces of Khiva, Atakent and Kyzylkum.
![image](https://user-images.githubusercontent.com/34010166/99827466-e5fea580-2b6e-11eb-98bd-cd6190985e7f.png)
And on the other hand, provinces like Constantinople, Cairo and Rome have _double_ effects due to being converted into several Vic2 provinces.
![image](https://user-images.githubusercontent.com/34010166/99827619-1b0af800-2b6f-11eb-8571-b7e287368e24.png)
This could be fixed by _summing_ when converting several provinces to one, and _distributing_ when converting one to several.
That would, however, raise the issue of major historic cities such as Constantinople getting split in 2 and losing their significance on the pop map 🤔.
Which could be countered by either changing the province mappings and having the famous provinces as 1 to 1 conversions, or by defining some ratio for these double results, like 7:3 Rome-Viterbo.
### EU4's Trade Goods
Oh coal, coal, coal.
With its massive trade value of 10, coal completely destroys the weight balance.
While it makes sense, as coal provinces are quite important and useful in EU4, it doesn't make much sense from Vic2's perspective. Moravia, with far less dev, has as much people as Prague... because it makes coal!
![image](https://user-images.githubusercontent.com/34010166/99829466-953c7c00-2b71-11eb-957d-033329d6a980.png)
(It's actually three times as much, since it's a 1:3 mapping 😅)
This would be fixed by not taking into factor the production income (value*produced), but just the goods produced. It would even make more sense, since Vic2 already has RGOs and there's no need to apply EU4's version of them into it in some way.
### China, India, and Others
Let's address the elephant in the room. China and India convert as complete wastelands, and the rest of the world gets a huge boost to its population numbers.
There's of course many fixes suggested to this, but the one I personally like is converting the total dev on a regional scale.
For example, we look at China's vanilla pop and redistribute it in China based on the EU4 province weights; instead of doing such with the whole world at once. 
I think to still keep it flexible, these regions should consist of one mega region encompassing most of the world, and some specific regions for where EU4's dev comes short of the regions' (usually massive) populations; like India, China, Korea-Japan, Manchuria, Indonesia, S/E Asia, Nigeria (and Sub-Sahara in general), Congo, Ethiopia, etc

Thanks for reading through my wall of text; I hope these suggestions were useful! 
I am personally capable of helping with the modding-related side of these; but unfortunately I have no idea how the converter code itself works.

**Comment by Zemurin** [comment] 2020-11-20 20:27
Hi, thanx for coming and pointing out these things. We're aware of them, as you guessed, but they are not as buggy as you may think. 

Before I go into details, keep in mind the only reason we even have this absolutely broken option of pop redistribution is because of legacy reasons; we have group members that play MP with flat dev so it doesn't matter if china is wasteland or not - as all players start with all provinces at 3 dev, those players that develop their provinces will get that increase in popcount during vic2. You may have notices trade good reshuffle option, that's intended to be used with this redistribution method to spice things up. 

This option is absolutely not meant to be used for any sane SP conversion, and redistributing pops according to regions is counterproductive for those players. 

Now, as far as distribution goes, I'm aware you don't speak C++ but this is closest to english as it gets:

![image](https://user-images.githubusercontent.com/2392697/99845342-c1a5c780-2b74-11eb-8e2f-8670fd15d3a4.png)

Now, what happens here:
- Pop distribution for a province is determined according to that province weight compared to the rest of the world combined. This weight as you know, includes trade goods, however it's an annoyingly complex calculation that looks into trade values, production and tax values, all modifiers a province has, modifiers to manpower, trade efficiency and so on. For the moment let's assume it works "fine" (except for coal).
- Then if the number of provinces we're mapping to is 2, we assign the province 55% of its intended value. Assumption is the other province in the pair will get also 55% of its own modified value, splitting this up.
- If there are 3 or more provinces we assign 1/X * 1.15 which would be about 40%, then 30% and so on.
These numbers are not there for accuracy but tweaked so they give reasonably acceptable numbers *for that MP group*.

This means that for any normal EU4->V2 set of provinces, even with extreme reshaping, the resulting V2 provinces will all be smaller as the pops are diluted across target ones.

Enter coal.

Remember that insanely complex function above? It appears to take trade value of the province, multiply by production multiplier, resulting in a range 15-25 (compared to 5-7 for regular goods), then multiplies it again by 1.5  just for good measure, then piled ontop building weights, manpower, taxes, and development modifier (now much you developed the province since 1444) and there's the final province weight.

The result can be 2x or 3x the amount of a normal province, indeed.

Well, I suppose we'll have to rework this mechanism one way or another.

**Comment by MaxTheDesertManIran** [comment] 2020-11-21 03:57
Then I suppose a new pop configuration, with summing for multiple -> one province mappings and a reworked province weight calculation and distribution method would be the answer, but it would also be a nightmare to implement I'm sure.

With the current system, however.

I have tested the dilution, and it does not seem to work.
![image](https://user-images.githubusercontent.com/34010166/99866495-db6ffa80-2bc6-11eb-93e3-206b8d9816fc.png)
![image](https://user-images.githubusercontent.com/34010166/99866479-b7acb480-2bc6-11eb-81c7-bfc76b71fbe6.png)
The pop stays almost the same, with only a difference of 0,01%. 

Based on that, my two cents is that it fails to properly get the number of vic2 provinces and ignores the if argument completely.

Tested with Stockholm as well, the same result. However; with the 1:3 mapping; one of the three provinces, Stockholm (the first one in the mapper), has 1.10% the population of others. I'm guessing Stockholm goes through it, but not the others?

Similar scenario in Moravia; with the first province defined in province_mappings.txt having 1.0 pop with the other two at 1.01% (the same ratio as the first and 2nd Istanbul)

I have no idea if this is useful or even makes sense, but here it is

**Comment by Zemurin** [comment] 2020-11-21 10:09
This is solid investigation. Please upload the Vic2 save you used t get these results here or on forums so I may reproduce and hopefully fix this.

**Comment by Zemurin** [comment] 2020-11-22 09:24
@MaxTheDesertManIran I have reworked this entirely in #626. Please grab the latest Picardy and see if the results make more sense now, and report back. If further tweaking is required I could use some input.

**Comment by MaxTheDesertManIran** [comment] 2020-11-24 08:54
I tested with the Qi build.
The new dev + building cost system is pretty solid, and the issue with coal is no more.

However, the single->multi province conversions are still not divided. 
(I saw that the if is gone from conversion)

I also see a problem with multi->single conversions, as they do not represent their EU4 equivalents properly.
I don't know how it's done currently, but here is my opinion:
Each Vic2 province should be checked for its EU4 equivalents, if there is more than one then the EU4 weights are summed up then given some sort of malus. (To avoid having it highly populated only because it equals five 3-dev ones in EU4 with regiment camps)

**Comment by Zemurin** [comment] 2020-11-24 09:08
We assign pops now according to the EU4 province weight. Weight is calculated, for extreme reshaping, as:
weight = total dev + total building cost * 0.01
This means a province with 30 dev, and some 2k gold in buildings will have a weight of 50.
Province with 3 dev and zero buildings weights 3, and should be getting about 15 times fewer pops than the province above.

Onto N-to-1 multimapping:
![image](https://user-images.githubusercontent.com/2392697/100071763-b506c500-2e3b-11eb-85ce-b3880e3def80.png)

Translated:
- For every eu4 province that maps to THIS V2 province, sum up its weight.
- Then divide the province weight by the number of incoming provinces (so /2 for 2, /3 for 3 etc) - averaging it out,
- Then go create pops. For all demographics coming from every EU4 province, scale them down by how much it weights, compared to all incoming provinces.

This means if we have a weight 3 and weight 30 eu4 provinces mapping to a vic2 province, the demographics from the 3-dev province will create 10 times fewer pops than from the other one. I would love to see you confirm this, as the math is trivial and should work well.

1-to-N mapping is problematic, as I'm now realizing that if we have a high-weight source province, it will map into multiple high-pop provinces directly. We should be scaling the weight according to the number of target provinces as well.

If you concur with my reasoning and can confirm this is indeed happening, I can add more code to address this issue.

Again thank you for helping me out!

**Comment by MaxTheDesertManIran** [comment] 2020-11-24 10:43
For the N-to-1 issue, I will examine Bukhara and Khiva in my game.
Based on the logs in this conversion: 
> Population per weight point is: 255201034 / 48312.2 = 5282.33
Bukhara got 137682 pops in my game, meaning it was given a weight of 26.
Khiva had 173741, meaning about 33 weight. 

Calculating by hand:
Bukhara would get 50+23+5+5 weight from dev; with 29 weight from 2900 ducats worth of buildings. So 112 in total.
Khiva would get 15+25 from dev, 20 from 2000 ducats of buildings. So 60 in total.

So it appears that the provinces are getting averaged. 112/4 = 28, close enough to 26; and 60/2 = 30, close enough to 33.
I suggest we remove the averaging stage to get full pops from these provinces, as what happens currently gives weighted ratios (the larger provinces' pops have more of a say), but an averaged population which causes unbalance for this region's dev-pop conversion.

On the 1-to-N matter, I have only noticed it with highly weighted provinces, so that may be the case.

**Comment by Zemurin** [comment] 2020-11-26 22:15
I believe this issue is now fixed. Please confirm.

**Comment by MaxTheDesertManIran** [comment] 2020-11-28 12:57
Yep, the issue is no longer.

**Comment by Zemurin** [comment] 2020-11-28 12:57
Thank you!

**Closed by Zemurin** 2020-11-28 12:57 UTC
