### ISSUE TITLE
For Windows 10 users What do you Suggest?My debug list down there

### ISSUE THREAD

**Issue by YuseinST** [ParadoxGameConverters/EU4toVic2#204] opened 2019-06-18 02:35 UTC
dear developers l have this debug issues when converting save files from eu4 my test saves taking these debugs listed below there 

2019-06-18 05:24:08    [INFO] Converter version 1.0Jprerelease
2019-06-18 05:24:08    [INFO] Built Mon Jun 17 20:38:12 2019
2019-06-18 05:24:08   [DEBUG]     Current directory is C:\Users\HÃ¼seyin Kurt\Desktop\EU4ToVic2\eu4tovic2
2019-06-18 05:24:08    [INFO] Using input file C:\Users\Hüseyin Kurt\Desktop\EU4ToVic2\Kurts1.eu4
2019-06-18 05:24:08    [INFO] Reading configuration file
2019-06-18 05:24:08   [DEBUG]     EU4 install path is D:\Steam\steamapps\common\Europa Universalis IV
2019-06-18 05:24:08   [DEBUG]     Victoria 2 install path is D:\Victoria.II.v3.04.Inclu.ALL.DLC\Victoria.II.v3.04.Inclu.ALL.DLC
2019-06-18 05:24:08   [DEBUG]     Victoria 2 documents directory is C:\Users\HÃ¼seyin Kurt\Documents\Paradox Interactive\Victoria II
2019-06-18 05:24:08    [INFO] Using output name Kurts1
2019-06-18 05:24:08    [INFO] * Importing EU4 save *
2019-06-18 05:24:08    [INFO] Building world

**Comment by Idhrendur** [comment] 2019-06-18 03:09
Unfortunately the converter doesn't handle paths with non-american characters very well. I'd suggest moving it out of your desktop folder to run it, perhaps to C:\. Your Vic2 documents directory might also be a problem, so maybe make a copy of it and point the converter at the copy?

**Comment by YuseinST** [comment] 2019-06-18 03:59
lm gonna try again with new paths with copies of debug files. l change my user name of my account as Yusein with latin alphabet l hope it works.if not l m planning to change my windows to downgrade win 8.1 what do youy think?

**Comment by Idhrendur** [comment] 2019-06-18 05:40
The Windows version is unlikely to make a difference. It's more a matter of American vs International Windows, and just making sure paths only have ASCII characters in them.

**Comment by brsclk77** [comment] 2019-06-18 14:33
Hi everyone,

This is what i got from the log file. It is much similar the case above. Could you please help me the solve the problem. The converter stuck while Building world. Btw, I do not use any non-US characters.

2019-06-18 17:29:22    [INFO] Converter version 1.0Jprerelease
2019-06-18 17:29:22    [INFO] Built Mon Jun 17 20:38:12 2019
2019-06-18 17:29:22   [DEBUG]     Current directory is C:\Program Files (x86)\Paradox Interactive\Converter\EU4ToVic2\eu4tovic2
2019-06-18 17:29:22    [INFO] Using input file C:\Users\toshiba-pc\Documents\Paradox Interactive\Europa Universalis IV\save games\England_Ice.eu4
2019-06-18 17:29:22    [INFO] Reading configuration file
2019-06-18 17:29:22   [DEBUG]     EU4 install path is C:\Program Files (x86)\Paradox Interactive\Europa Universalis IV
2019-06-18 17:29:22   [DEBUG]     Victoria 2 install path is C:\Program Files (x86)\Paradox Interactive\Pop Demand II
2019-06-18 17:29:22   [DEBUG]     Victoria 2 documents directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Victoria II
2019-06-18 17:29:22    [INFO] Using output name England_Ice
2019-06-18 17:29:22    [INFO] * Importing EU4 save *
2019-06-18 17:29:22   [DEBUG]     Get EU4 Mods
2019-06-18 17:29:22   [DEBUG]     Get EU4 Mod Directory
2019-06-18 17:29:22   [DEBUG]     EU4 Documents directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Europa Universalis IV
2019-06-18 17:29:22   [DEBUG]     Get CK2 Export Directory
2019-06-18 17:29:22   [DEBUG]     CK2 export directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod
2019-06-18 17:29:22   [DEBUG]     EU4 Mod is at C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod/Converted_England1011_10_04
2019-06-18 17:29:22    [INFO] Building world

**Comment by YuseinST** [comment] 2019-06-18 14:43
> Hi everyone,
> 
> This is what i got from the log file. It is much similar the case above. Could you please help me the solve the problem. The converter stuck while Building world. Btw, I do not use any non-US characters.
> 
> 2019-06-18 17:29:22 [INFO] Converter version 1.0Jprerelease
> 2019-06-18 17:29:22 [INFO] Built Mon Jun 17 20:38:12 2019
> 2019-06-18 17:29:22 [DEBUG] Current directory is C:\Program Files (x86)\Paradox Interactive\Converter\EU4ToVic2\eu4tovic2
> 2019-06-18 17:29:22 [INFO] Using input file C:\Users\toshiba-pc\Documents\Paradox Interactive\Europa Universalis IV\save games\England_Ice.eu4
> 2019-06-18 17:29:22 [INFO] Reading configuration file
> 2019-06-18 17:29:22 [DEBUG] EU4 install path is C:\Program Files (x86)\Paradox Interactive\Europa Universalis IV
> 2019-06-18 17:29:22 [DEBUG] Victoria 2 install path is C:\Program Files (x86)\Paradox Interactive\Pop Demand II
> 2019-06-18 17:29:22 [DEBUG] Victoria 2 documents directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Victoria II
> 2019-06-18 17:29:22 [INFO] Using output name England_Ice
> 2019-06-18 17:29:22 [INFO] * Importing EU4 save *
> 2019-06-18 17:29:22 [DEBUG] Get EU4 Mods
> 2019-06-18 17:29:22 [DEBUG] Get EU4 Mod Directory
> 2019-06-18 17:29:22 [DEBUG] EU4 Documents directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Europa Universalis IV
> 2019-06-18 17:29:22 [DEBUG] Get CK2 Export Directory
> 2019-06-18 17:29:22 [DEBUG] CK2 export directory is C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod
> 2019-06-18 17:29:22 [DEBUG] EU4 Mod is at C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod/Converted_England1011_10_04
> 2019-06-18 17:29:22 [INFO] Building world

l also changed my account name with English letters still taking same issue lm using latest converter 1.0j  
also, change eu4 back to version 1.27.2 l hope someone gives us a solution l am planning a mega campaing from ck2 to eu4 to vic2 and to hoi4

**Comment by Idhrendur** [comment] 2019-06-18 19:52
Okay, so it's not the paths. You might want to check on the forum thread, the people there have some ideas and we're working on getting the converter itself updated.

**Comment by IhateTrains** [comment] 2019-06-18 20:35
Is this path even correct? There's one slash instead of backslash in 

> C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod/Converted_England1011_10_04

**Comment by Idhrendur** [comment] 2019-06-18 20:37
> Is this path even correct? There's one slash instead of backslash in
> 
> > C:\Users\toshiba-pc\Documents\Paradox Interactive\Crusader Kings II\eu4_export\mod/Converted_England1011_10_04

Yep! Windows actually doesn't care about backslash vs slash, so the converter tries to use forward slashes for the sake of linux users. That can lead to these cases where both types of slash are in a path.

**Comment by brsclk77** [comment] 2019-06-19 06:17
[England_Ice.zip](https://github.com/ParadoxGameConverters/EU4toVic2/files/3304625/England_Ice.zip)

Could you please have a look at the attached file? I really wonder what the problem is. Because i still believe that something from my side is wrong. The save file was converted to EU4 "1.28.3" from CK2.

**Comment by Idhrendur** [comment] 2019-06-19 14:57
Honestly, it just sounds life you have the usual problems people are having right now. If you go tu the forum thread, people know how to work around them.

**Closed by Idhrendur** 2019-06-19 14:57 UTC
